apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: put79smhe-nodejs
  janus-idp.io/tekton: put79smhe-nodejs
  backstage.io/kubernetes-id: put79smhe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: put79smhe-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
